### ISSUE TITLE
[建议]加入Mythicmobs怪物掉落

### ISSUE THREAD

**Issue by 1649915200** [Saukiya/SX-Item#10]
希望加入Mythicmobs怪物掉落即：
Drop:
- si 铁剑 1 0.5
- sx 铁剑 1 0.5

**Comment by Saukiya** [comment]
该功能已存在，详细可以看该链接
https://github.com/Saukiya/SX-Item/blob/master/src/main/java/github/saukiya/sxitem/helper/MythicMobsHelper.java

**Comment by Saukiya** [comment]
等明天？或者后天发个修复过Mythicmoba的包吧，发现目前3.1.8版本没做更新

**Comment by Saukiya** [comment]
已修复: [3.2.2](https://github.com/Saukiya/SX-Item/releases/tag/3.2.2)
