### ISSUE TITLE
NBT类型问题

### ISSUE THREAD

**Issue by apCoko** [Saukiya/SX-Item#24]
我在使用一款LegendaryRunePlus插件，它是通过读取NBT来得到资料
我通过编写
NBT:
    LegendaryRunePlus_Level: <l:天赋卡等级>
按道理<l:天赋卡等级>转化为整数, 物品读取出来的NBT类型应该是int，可实际上却是STRING
因为类型不是int导致其它插件无法正确读取。
![image](https://github.com/user-attachments/assets/5dd1c7b3-5788-469a-9bc2-fdda44927953)

不知道有没有直接修改指定行nbt类型的写法，或是更新一下？  感谢。

**Comment by Saukiya** [comment]
目前随机功能主要还是针对字符串, 类似<?:>结构返回的 都是字符串类型

这对使用上确实有一些影响, 我这边可能会尝试优化下结构?

**Comment by apCoko** [comment]
感谢回复，我会持续关注的。

**Comment by Saukiya** [comment]
已增加 [4.2.0](https://github.com/Saukiya/SX-Item/releases/tag/4.2.0)
具体可看Default-3测试用例
